#include <iostream>
#include <cstdlib>
#include <ctime>
using namespace std;
int main()
{
	int randomNumber, number;
	srand(time(0));
	randomNumber = rand() % 100 + 1;
	cout << "\t\tGUESSING GAME \n"<<endl;
	while(number != randomNumber)
	{
		cout << "Guess the number generated by the computer: ";
		cin >> number;
		if (number < randomNumber)
			cout << "Too Small\n";
		else if (number > randomNumber)
			cout << "Too big\n";
		else if (number = randomNumber)
			cout << "\nCongratulation!! You got the correct number."<<endl;
	}
	return 0;
}
